t1 = (['5207 S Greenwood Chicago IL 60615',
  '  1210 E Hyde Park Blvd Chicago IL 60615'],
 ['grocery', 'bank'],
 {'bicycling': 'high',
  'cta': 'medium',
  'divvy': 'high',
  'driving': 'medium',
  'shuttles': 'low',
  'walking': 'medium'},
 'hyde_park',
 'yes')

t2 = (['5105 South Harper Ave Chicago IL 60615'],
 ['medical center'],
 {'bicycling': 'medium',
  'cta': 'high',
  'divvy': 'low',
  'driving': 'medium',
  'shuttles': 'low',
  'walking': 'none'},
 'neither',
 'no')

 t3 = (['1005 E 60th Street'],
 ['drug store'],
 {'bicycling': 'medium',
  'cta': 'medium',
  'divvy': 'none',
  'driving': 'medium',
  'shuttles': 'medium',
  'walking': 'none'},
 'downtown',
 'yes')
 
 t4 = (['1005 E 60th Street'],
 ['drug store'],
 {'bicycling': 'medium',
  'cta': 'none',
  'divvy': 'medium',
  'driving': 'medium',
  'shuttles': 'none',
  'walking': 'none'},
 'downtown',
 'yes')
 
 t5 = (['1005 E 60th Street'],
 [],
 {'bicycling': 'medium',
  'cta': 'none',
  'divvy': 'medium',
  'driving': 'medium',
  'shuttles': 'none',
  'walking': 'none'},
 'downtown',
 'yes')

