# Generated by Django 2.0.2 on 2018-03-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetad', models.TextField()),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitpref', models.CharField(max_length=500)),
                ('destpref', models.CharField(max_length=500)),
                ('interests', models.TextField()),
            ],
        ),
    ]
